### ISSUE TITLE
columns should probably scroll individually

### ISSUE THREAD

**Issue by robx** [alicebob/siren#34]
If I scroll down a long list of directories, then select one, the content is loaded fine in the next column over, but I can't actually see any change except the little selection arrow showing up. Perhaps the columns should scroll by themselves? Or selecting something scrolls up?

**Comment by alicebob** [comment]
They used to do that, and that's how it should work indeed :)

**Comment by robx** [comment]
this seems fixed, might have just been on a broken branch
