### ISSUE TITLE
empty string list entries not high enough

### ISSUE THREAD

**Issue by robx** [alicebob/siren#36]
![screen shot 2018-02-08 at 19 05 04](https://user-images.githubusercontent.com/132113/35990026-14ca3394-0d03-11e8-86d2-29569762556c.png)
![screen shot 2018-02-08 at 19 05 10](https://user-images.githubusercontent.com/132113/35990031-17c4e152-0d03-11e8-9556-80b178e635db.png)

(maybe better to fix this by putting in some kind of "&lt;unknown artist>"?)

**Comment by alicebob** [comment]
<script>alert("foo")</script>
